# Generated by Django 4.2.15 on 2024-08-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0002_remove_document_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='named_entities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='sentiment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='text_classification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processedtext',
            name='processed_data',
            field=models.TextField(),
        ),
    ]
